import type { Metadata } from "next";
import "./globals.css";
import { Public_Sans } from 'next/font/google'

const PS = Public_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Demo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={PS.className}
      >
        {children}
      </body>
    </html>
  );
}
